trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: asottile
      type: github
      endpoint: github
      name: asottile/azure-pipeline-templates
      ref: refs/tags/v0.0.8

jobs:
- template: job--pre-commit.yml@asottile
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py27, py37]
    os: windows
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [pypy, pypy3, py27, py36, py37]
    os: linux
